version: '3.8'

services:
  bot-whatsapp-guardian:
    build:
      context: .
    container_name: bot-whatsapp-guardian
    restart: unless-stopped
    volumes:
      - .:/app
    environment:
      - NODE_ENV=production